packages:
  - apps/*
  - packages/*
allowBuilds:
  '@scarf/scarf': false
  '@swc/core': false
  cpu-features: false
  esbuild: true
  protobufjs: false
  ssh2: false
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.7'
  - '@turbo/darwin-arm64@2.11.7'
  - '@turbo/linux-64@2.11.7'
  - '@turbo/linux-arm64@2.11.7'
  - '@turbo/windows-64@2.11.7'
  - '@turbo/windows-arm64@2.11.7'
  - turbo@2.11.7
  - nestjs-pino@5.3.0
  - supertest@7.3.1
  - '@tanstack/query-core@5.104.1'
  - '@tanstack/react-query@5.104.1'
