import { index, jsonb, pgSchema, text, timestamp, uuid } from 'drizzle-orm/pg-core';

export const audit = pgSchema('audit');

export const auditActorType = audit.enum('actor_type', ['USER', 'ADMIN', 'SYSTEM']);

/**
 * Insert-only (enforced in SQL: trigger + grants, see the migration). Admin actions and admin reads of
 * sensitive data (documents, pick-up records) write here (CLAUDE.md rule 5). No coordinates, no PII values.
 */
export const auditLogs = audit.table(
  'audit_logs',
  {
    id: uuid('id').primaryKey(), // UUIDv7, generated by the app
    actorType: auditActorType('actor_type').notNull(),
    actorUserId: uuid('actor_user_id'),
    action: text('action').notNull(),
    targetType: text('target_type'),
    targetId: text('target_id'),
    metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('audit_logs_target_idx').on(t.targetType, t.targetId),
    index('audit_logs_actor_idx').on(t.actorUserId),
    index('audit_logs_created_at_idx').on(t.createdAt),
  ],
);
